
kind: "Service"
apiVersion: "v1"
metadata:
  name: "hello-dom1-service"
  labels:
    demoservice: "yes"
    owner: "ddastoli"
spec:
  selector:
    demoscript: "yes"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088
  clusterIP: 172.30.95.2
  loadBalancerIP: 172.29.155.2
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.147.1
